TRUNCATE TABLE notes CASCADE;
INSERT INTO notes (user_id, folder_id, name, content)
VALUES
('1', '1', 'note name', 'Pynchon attended Oyster Bay High School in Oyster Bay, where he was awarded "student of the year" and contributed short fictional pieces to his school newspaper. These juvenilia incorporated some of the literary motifs and recurring subject matter he would use throughout his career: oddball names, sophomoric humor, illicit drug use, and paranoia.'),
('1', '1', 'note name', 'Thomas Pynchon was born in 1937 in Glen Cove, Long Island, New York, one of three children of Thomas Ruggles Pynchon Sr. (1907–1995) and Katherine Frances Bennett (1909–1996). His earliest American ancestor, William Pynchon, emigrated to the Massachusetts Bay Colony with the Winthrop Fleet in 1630, then became the founder of Springfield, Massachusetts in 1636, and thereafter a long line of Pynchon descendants found wealth and repute on American soil. Aspects of Pynchons ancestry and family background have partially inspired his fiction writing, particularly in the Slothrop family histories related in the short story "The Secret Integration" (1964) and Gravitys Rainbow (1973). Pynchon was raised a Catholic.'),
('1', '1', 'note name', 'After graduating from high school in 1953 at the age of 16, Pynchon studied engineering physics at Cornell University, but left at the end of his second year to serve in the U.S. Navy. In 1957, he returned to Cornell to pursue a degree in English. His first published story, "The Small Rain", appeared in the Cornell Writer in March 1959, and narrates an actual experience of a friend who had served in the Army; subsequently, however, episodes and characters throughout Pynchons fiction draw freely upon his own experiences in the Navy.'),
('1', '2', 'note name', 'While at Cornell, Pynchon started his friendships with Richard Fariña and David Shetzline; Pynchon would go on to dedicate Gravitys Rainbow to Fariña, as well as serve as his best man and as his pallbearer. Together the two briefly led what Pynchon has called a "micro-cult" around Oakley Halls 1958 novel Warlock.'),
('1', '2', 'note name', 'Pynchon later reminisced about his college days in the introduction he wrote in 1983 for Fariñas novel Been Down So Long It Looks Like Up to Me, first published in 1966. He reportedly attended lectures given by Vladimir Nabokov, who then taught literature at Cornell.'),
('1', '2', 'note name', 'Although Nabokov later said that he had no memory of Pynchon, Nabokovs wife Véra, who graded her husbands class papers, commented that she remembered his distinctive handwriting as a mixture of printed and cursive letters, "half printing, half script."[9][10] In 1958, Pynchon and classmate Kirkpatrick Sale wrote part or all of a science-fiction musical, Minstrel Island, which portrayed a dystopian future in which IBM rules the world.'),
('1', '3', 'note name', 'After leaving Cornell, Pynchon began to work on his first novel: V. From February 1960 to September 1962, he was employed as a technical writer at Boeing in Seattle, where he compiled safety articles for the Bomarc Service News, a support newsletter for the BOMARC surface-to-air missile deployed by the U.S. Air Force.'),
('1', '3', 'note name', 'Pynchons experiences at Boeing inspired his depictions of the "Yoyodyne" corporation in V. and The Crying of Lot 49, and both his background in physics and the technical journalism he undertook at Boeing provided much raw material for Gravitys Rainbow.'),
('1', '3', 'note name', 'When published in 1963, V. won a William Faulkner Foundation Award for the best first novel of the year. (It was a finalist for the National Book Award.)'),
('2', '4', 'note name', 'note content'),
('2', '4', 'note name', 'note content'),
('2', '4', 'note name', 'note content'),
('2', '5', 'note name', 'note content'),
('2', '5', 'note name', 'note content'),
('2', '5', 'note name', 'note content'),
('2', '6', 'note name', 'note content'),
('2', '6', 'note name', 'note content'),
('2', '6', 'note name', 'note content'),
('3', '7', 'note name', 'note content'),
('3', '7', 'note name', 'note content'),
('3', '7', 'note name', 'note content'),
('3', '8', 'note name', 'note content'),
('3', '8', 'note name', 'note content'),
('3', '8', 'note name', 'note content'),
('3', '9', 'note name', 'note content'),
('3', '9', 'note name', 'note content'),
('3', '9', 'note name', 'note content')
;